server:
  port: 9000

spring:
  application:
    name: cards

  profiles:
    active: development

  config:
    import: optional:configserver:http://localhost:8071/

  datasource:
    url: jdbc:mysql://localhost:3308/cards-database
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema/card-schema.sql

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"