server:
  port: 8072

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

management:
  info:
    env:
      enabled: true

  endpoint:
    gateway:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  application:
    name: api-gateway-microservice
    description: Askie01's api-gateway microservice
    version: 1.0.0

logging:
  level:
    com:
      askie01:
        apigateway: DEBUG