server:
  port: 8072

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          httpclient:
            connect-timeout: 1000
            response-timeout: 1s

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s

management:
  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    gateway:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

info:
  application:
    name: api-gateway-microservice
    description: Askie01's api-gateway microservice
    version: 1.0.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"