server:
  port: 8072

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

management:
  info:
    env:
      enabled: true

  endpoint:
    gateway:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

info:
  application:
    name: api-gateway-microservice
    description: Askie01's api-gateway microservice
    version: 1.0.0

logging:
  level:
    com:
      askie01:
        apigateway: DEBUG