server:
  port: 8090

spring:
  application:
    name: loans

  profiles:
    active: development

  config:
    import: optional:configserver:http://localhost:8071/

  datasource:
    url: jdbc:mysql://localhost:3307/loans-database
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:schema/loan-schema.sql

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"