server:
  port: 8090

spring:
  application:
    name: loans

  profiles:
    active: development

  config:
    import: optional:configserver:http://localhost:8071/

  datasource:
    url: jdbc:mysql://localhost:3307/loans-database
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      schema-locations: classpath:schema/loan-schema.sql

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  info:
    env:
      enabled: true

  endpoint:
    shutdown:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  application:
    name: loans-microservice
    description: Askie01's loans microservice
    version: 1.0.0