apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-server-deployment
  labels:
    app: configuration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-server
  template:
    metadata:
      labels:
        app: configuration-server
    spec:
      containers:
        - name: configuration-server
          image: askie01/configuration-server:latest
          ports:
            - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-server
spec:
  selector:
    app: configuration-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
