services:

  accounts:
    image: "askie01/accounts:latest"
    container_name: "accounts-microservice"
    extends:
      file: ./configuration/accounts-microservice-configuration.yaml
      service: accounts-microservice-configuration

  accounts-database:
    image: "mysql:latest"
    container_name: "accounts-database"
    extends:
      file: ./configuration/accounts-database-configuration.yaml
      service: accounts-database-configuration

  loans:
    image: "askie01/loans:latest"
    container_name: "loans-microservice"
    extends:
      file: ./configuration/loans-microservice-configuration.yaml
      service: loans-microservice-configuration

  loans-database:
    image: "mysql:latest"
    container_name: "loans-database"
    extends:
      file: ./configuration/loans-database-configuration.yaml
      service: loans-database-configuration

  cards:
    image: "askie01/cards:latest"
    container_name: "cards-microservice"
    extends:
      file: ./configuration/cards-microservice-configuration.yaml
      service: cards-microservice-configuration

  cards-database:
    image: "mysql:latest"
    container_name: "cards-database"
    extends:
      file: ./configuration/cards-database-configuration.yaml
      service: cards-database-configuration

  configuration-server:
    image: "askie01/configuration-server:latest"
    container_name: "configuration-server-microservice"
    extends:
      file: ./configuration/configuration-server-microservice-configuration.yaml
      service: configuration-server-microservice-configuration

  discovery-server:
    image: "askie01/discovery-server:latest"
    container_name: "discovery-server-microservice"
    extends:
      file: ./configuration/discovery-server-configuration.yaml
      service: discovery-server-microservice-configuration

  api-gateway:
    image: "askie01/api-gateway:latest"
    container_name: "api-gateway-microservice"
    extends:
      file: ./configuration/api-gateway-microservice-configuration.yaml
      service: api-gateway-microservice-configuration

  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: "rabbitmq"
    extends:
      file: ./configuration/rabbitmq-configuration.yaml
      service: rabbitmq-configuration

  redis:
    image: "redis:latest"
    container_name: "redis"
    extends:
      file: ./configuration/redis-configuration.yaml
      service: redis-configuration

  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: "keycloak"
    command: "start-dev --import-realm"
    extends:
      file: ./configuration/keycloak-configuration.yaml
      service: keycloak-configuration

  keycloak-database:
    image: "mysql:latest"
    container_name: "keycloak-database"
    extends:
      file: configuration/keycloak-database-configuration.yaml
      service: keycloak-database-configuration

  tempo:
    image: "grafana/tempo:latest"
    container_name: "tempo"
    command: [ "-config.file=/etc/tempo.yaml" ]
    extends:
      file: ./configuration/tempo-configuration.yaml
      service: tempo-configuration

  prometheus:
    image: "prom/prometheus:latest"
    container_name: "prometheus"
    extends:
      file: ./configuration/prometheus-configuration.yaml
      service: prometheus-configuration

  minio:
    image: "minio/minio:latest"
    container_name: "minio-storage"
    extends:
      file: ./configuration/minio-configuration.yaml
      service: minio-configuration

  read:
    image: "grafana/loki:latest"
    container_name: "loki-read"
    extends:
      file: ./configuration/loki-read-configuration.yaml
      service: loki-read-configuration
    networks: &loki-dns
      microservices-network:
        aliases:
          - loki

  write:
    image: "grafana/loki:latest"
    container_name: "loki-write"
    extends:
      file: ./configuration/loki-write-configuration.yaml
      service: loki-write-configuration
    networks:
      <<: *loki-dns

  gateway:
    image: "nginx:latest"
    container_name: "loki-gateway"
    extends:
      file: ./configuration/loki-gateway-configuration.yaml
      service: loki-gateway-configuration

  backend:
    image: "grafana/loki:latest"
    container_name: "loki-backend"
    extends:
      file: ./configuration/loki-backend-configuration.yaml
      service: loki-backend-configuration

  grafana:
    image: "grafana/grafana:latest"
    container_name: "grafana-search"
    extends:
      file: ./configuration/grafana-configuration.yaml
      service: grafana-configuration

  alloy:
    image: "grafana/alloy:latest"
    container_name: "grafana-alloy"
    extends:
      file: ./configuration/alloy-configuration.yaml
      service: alloy-configuration

networks:
  microservices-network:
    driver: "bridge"