services:
  network-configuration:
    networks:
      - "microservices-tutorial"

  standard-microservice-configuration:
    extends:
      service: network-configuration

    deploy:
      resources:
        limits:
          memory: 700m

    environment:
      - "spring.rabbitmq.host=rabbitmq"

    depends_on:
      rabbitmq:
        condition: service_healthy

  configuration-server-connection-configuration:
    extends:
      service: standard-microservice-configuration

    depends_on:
      configuration-server:
        condition: service_healthy

    environment:
      - "spring.config.import=configserver:http://configuration-server:8071"