services:

  accounts:
    image: "askie01/accounts:latest"
    container_name: "accounts-microservice"
    ports:
      - "8080:8080"
    environment:
      - "spring.profiles.active=quality-assurance"
    extends:
      file: docker-compose-common-configuration.yaml
      service: accounts-microservice-configuration
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  accounts-database:
    image: "mysql:latest"
    container_name: "accounts-database"
    ports:
      - "3306:3306"
    extends:
      file: docker-compose-common-configuration.yaml
      service: accounts-database-configuration
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  loans:
    image: "askie01/loans:latest"
    container_name: "loans-microservice"
    ports:
      - "8090:8090"
    environment:
      - "spring.profiles.active=quality-assurance"
    extends:
      file: docker-compose-common-configuration.yaml
      service: loans-microservice-configuration
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  loans-database:
    image: "mysql:latest"
    container_name: "loans-database"
    ports:
      - "3307:3306"
    extends:
      file: docker-compose-common-configuration.yaml
      service: loans-database-configuration
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  cards:
    image: "askie01/cards:latest"
    container_name: "cards-microservice"
    ports:
      - "9000:9000"
    environment:
      - "spring.profiles.active=quality-assurance"
    extends:
      file: docker-compose-common-configuration.yaml
      service: cards-microservice-configuration
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  cards-database:
    image: "mysql:latest"
    container_name: "cards-database"
    ports:
      - "3308:3306"
    extends:
      file: docker-compose-common-configuration.yaml
      service: cards-database-configuration
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  configuration-server:
    image: "askie01/configuration-server:latest"
    container_name: "configuration-server-microservice"
    ports:
      - "8071:8071"
    extends:
      file: docker-compose-common-configuration.yaml
      service: configuration-server-microservice-configuration
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    image: "askie01/discovery-server:latest"
    container_name: "discovery-server-microservice"
    ports:
      - "8070:8070"
    extends:
      file: docker-compose-common-configuration.yaml
      service: discovery-server-microservice-configuration
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: "askie01/api-gateway:latest"
    container_name: "api-gateway-microservice"
    ports:
      - "8072:8072"
    extends:
      file: docker-compose-common-configuration.yaml
      service: api-gateway-microservice-configuration
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: docker-compose-common-configuration.yaml
      service: rabbitmq-configuration

networks:
  microservices-network:
    driver: "bridge"