services:

  accounts:
    image: "askie01/accounts:latest"
    container_name: "accounts-microservice"
    extends:
      file: ./configuration/accounts-microservice-configuration.yaml
      service: accounts-microservice-configuration
    env_file:
      path: ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  accounts-database:
    image: "mysql:latest"
    container_name: "accounts-database"
    extends:
      file: ./configuration/accounts-database-configuration.yaml
      service: accounts-database-configuration
    env_file:
      - configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  loans:
    image: "askie01/loans:latest"
    container_name: "loans-microservice"
    extends:
      file: ./configuration/loans-microservice-configuration.yaml
      service: loans-microservice-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  loans-database:
    image: "mysql:latest"
    container_name: "loans-database"
    extends:
      file: ./configuration/loans-database-configuration.yaml
      service: loans-database-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  cards:
    image: "askie01/cards:latest"
    container_name: "cards-microservice"
    extends:
      file: ./configuration/cards-microservice-configuration.yaml
      service: cards-microservice-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  cards-database:
    image: "mysql:latest"
    container_name: "cards-database"
    extends:
      file: ./configuration/cards-database-configuration.yaml
      service: cards-database-configuration
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  configuration-server:
    image: "askie01/configuration-server:latest"
    container_name: "configuration-server-microservice"
    extends:
      file: ./configuration/configuration-server-microservice-configuration.yaml
      service: configuration-server-microservice-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    image: "askie01/discovery-server:latest"
    container_name: "discovery-server-microservice"
    extends:
      file: ./configuration/discovery-server-configuration.yaml
      service: discovery-server-microservice-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: "askie01/api-gateway:latest"
    container_name: "api-gateway-microservice"
    extends:
      file: ./configuration/api-gateway-microservice-configuration.yaml
      service: api-gateway-microservice-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: "rabbitmq"
    extends:
      file: ./configuration/rabbitmq-configuration.yaml
      service: rabbitmq-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:latest"
    container_name: "redis"
    extends:
      file: ./configuration/redis-configuration.yaml
      service: redis-configuration
    env_file:
      - ./configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: "quay.io/keycloak/keycloak:latest"
    container_name: "keycloak"
    command: "start-dev --import-realm"
    extends:
      file: ./configuration/common-configuration.yaml
      service: common-configuration
    env_file:
      - ./configuration/environment/development.env

  keycloak-database:
    image: "mysql:latest"
    container_name: "keycloak-database"
    extends:
      file: configuration/keycloak-database-configuration.yaml
      service: keycloak-database-configuration
    env_file:
      - configuration/environment/development.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: "minio/minio:latest"
    container_name: "minio-storage"
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9000"
    volumes:
      - ./observability/.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - microservices-network

  read:
    image: "grafana/loki:latest"
    container_name: "loki-read"
    command: "-config.file=/etc/loki/config.yaml -target=read"
    ports:
      - "3101:3100"
      - "7946"
      - "9095"
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: &loki-dns
      microservices-network:
        aliases:
          - loki

  write:
    image: "grafana/loki:latest"
    container_name: "loki-write"
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - "3102:3100"
      - "7946"
      - "9095"
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      <<: *loki-dns

  gateway:
    image: "nginx:latest"
    container_name: "loki-gateway"
    depends_on:
      - read
      - write
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/nginx.conf
        user  nginx;
        worker_processes  5;  ## Default: 1

        events {
          worker_connections   1000;
        }

        http {
          resolver 127.0.0.11;

          server {
            listen             3100;

            location = / {
              return 200 'OK';
              auth_basic off;
            }

            location = /api/prom/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /api/prom/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /api/prom/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }

            location = /loki/api/v1/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /loki/api/v1/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /loki/api/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }
          }
        }
        EOF
        /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - "3100:3100"
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  backend:
    image: "grafana/loki:latest"
    container_name: "loki-backend"
    volumes:
      - ./observability/loki/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    depends_on:
      - gateway
    networks:
      - microservices-network

  grafana:
    image: "grafana/grafana:latest"
    container_name: "grafana-search"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - gateway
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
    ports:
      - "3000:3000"
    volumes:
      - ./observability/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./observability/.data/grafana:/var/lib/grafana
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  alloy:
    image: "grafana/alloy:latest"
    container_name: "grafana-alloy"
    volumes:
      - ./observability/alloy/alloy-local-config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    depends_on:
      - gateway
    networks:
      - microservices-network

  prometheus:
    image: "prom/prometheus:latest"
    container_name: "prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    extends:
      file: ./configuration/common-configuration.yaml
      service: common-configuration

  tempo:
    image: "grafana/tempo:latest"
    container_name: "tempo"
    command: [ "-config.file=/etc/tempo.yaml" ]
    ports:
      - "3110:3100"
      - "4318:4318"
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo.yaml
    extends:
      file: ./configuration/common-configuration.yaml
      service: common-configuration

networks:
  microservices-network:
    driver: "bridge"