services:

  network-configuration:
    networks:
      - "microservices-network"

  common-microservice-configuration:
    extends:
      service: network-configuration

    deploy:
      resources:
        limits:
          memory: 700m

    environment:
      - "spring.rabbitmq.host=rabbitmq"

    depends_on:
      rabbitmq:
        condition: service_healthy

  accounts-microservice-configuration:
    extends:
      service: common-microservice-configuration

    environment:
      - "spring.config.import=configserver:http://configuration-server:8071"

    depends_on:
      configuration-server:
        condition: service_healthy

      accounts-database:
        condition: service_healthy

  loans-microservice-configuration:
    extends:
      service: common-microservice-configuration

    environment:
      - "spring.config.import=configserver:http://configuration-server:8071"

    depends_on:
      configuration-server:
        condition: service_healthy

      loans-database:
        condition: service_healthy

  cards-microservice-configuration:
    extends:
      service: common-microservice-configuration

    environment:
      - "spring.config.import=configserver:http://configuration-server:8071"

    depends_on:
      configuration-server:
        condition: service_healthy

      cards-database:
        condition: service_healthy