services:

  alloy-configuration:
    extends:
      file: common-configuration.yaml
      service: common-configuration

    ports:
      - "12345:12345"

    command: "run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy"

    volumes:
      - "../observability/alloy/alloy-local-config.yaml:/etc/alloy/config.alloy:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

    depends_on:
      - gateway