services:

  cards-database-configuration:
    extends:
      file: common-configuration.yaml
      service: common-configuration

    ports:
      - "${cards_database_exposed_port}:3306"

    volumes:
      - "../../sql/cards/schema:/docker-entrypoint-initdb.d"
      - "../../sql/cards/data/${environment}:/var/lib/mysql"

    environment:
      - "MYSQL_USER=${cards_database_username}"
      - "MYSQL_PASSWORD=${cards_database_password}"
      - "MYSQL_DATABASE=cards"
      - "MYSQL_ROOT_PASSWORD=${cards_database_root_password}"

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5