services:

  cards-microservice-configuration:
    extends:
      file: microservice-configuration.yaml
      service: microservice-configuration

    ports:
      - "${cards_microservice_exposed_port}:${cards_microservice_port}"

    environment:
      - "server.port=${cards_microservice_port}"
      - "spring.profiles.active=${cards_microservice_active_profiles}"
      - "spring.config.import=configserver:http://configuration-server:${configuration_server_microservice_port}"
      - "spring.datasource.url=jdbc:mysql://cards-database:3306/cards"
      - "spring.datasource.username=${cards_database_username}"
      - "spring.datasource.password=${cards_database_password}"
      - "eureka.client.service-url.defaultZone=http://discovery-server:${discovery_server_microservice_port}/eureka/"
      - "spring.rabbitmq.host=rabbitmq"

    depends_on:
      rabbitmq:
        condition: service_healthy

      configuration-server:
        condition: service_healthy

      cards-database:
        condition: service_healthy

      discovery-server:
        condition: service_healthy