services:

  discovery-server-microservice-configuration:
    extends:
      file: microservice-configuration.yaml
      service: microservice-configuration

    ports:
      - "${discovery_server_microservice_exposed_port}:${discovery_server_microservice_port}"

    environment:
      - "server.port=${discovery_server_microservice_port}"
      - "spring.config.import=configserver:http://configuration-server:${configuration_server_microservice_port}"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      configuration-server:
        condition: service_healthy