services:

  loans-database-configuration:
    extends:
      file: common-configuration.yaml
      service: common-configuration

    ports:
      - "${loans_database_exposed_port}:3306"

    volumes:
      - "../../sql/loans/schema:/docker-entrypoint-initdb.d"
      - "../../sql/loans/data/${environment}:/var/lib/mysql"

    environment:
      - "MYSQL_USER=${loans_database_username}"
      - "MYSQL_PASSWORD=${loans_database_password}"
      - "MYSQL_DATABASE=loans"
      - "MYSQL_ROOT_PASSWORD=${loans_database_root_password}"

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5