services:

  redis-configuration:
    extends:
      file: common-configuration.yaml
      service: common-configuration

    ports:
      - "${redis_database_exposed_port}:6379"

    depends_on:
      grafana:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5